name: expenso
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  dio: ^4.0.4
  pretty_dio_logger: ^1.1.1
  google_fonts: ^2.3.1
  logger: ^1.1.0
  intl: ^0.17.0
  smooth_page_indicator: ^1.0.0+2
  flutter_easyloading: ^3.0.3
  flutter_svg: ^1.0.3
  lottie: ^1.2.2
  rxdart: ^0.26.0
  pinput: ^2.1.4
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  intl_phone_field: ^3.1.0
  syncfusion_flutter_core: ^20.2.44
  syncfusion_flutter_sliders: ^20.2.44
  flutter_spinkit: ^5.1.0
  connectivity_plus: ^2.3.6
  wakelock: ^0.6.2
  permission_handler: ^10.0.0
  uuid: ^3.0.6
  flutter: 
    sdk: flutter
 

dev_dependencies: 
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  hive_generator: ^1.1.2
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

